Control Structure - change presentation and add exe
RedHat-Israel/ROSE pull request #342
Opened 2020-08-24 10:32 UTC by shiramax

2020-08-30 08:39 UTC, shiramax commented
@sleviim please review :)

2020-08-30 11:09 UTC, sleviim requested changes

2020-08-30 11:09 UTC, sleviim commented on docs/course_materials/control_structures.html
> +                      For example user given 10 so the output should be 55
For example, for receiving 10, the output should be 55.

2020-08-30 11:09 UTC, sleviim commented on docs/course_materials/control_structures.html
> +                    <h3><b>Extra - Nested Loop</b></h3>
What about adding a slide with 'Extra' before that?

2020-09-08 06:40 UTC, shiramax commented on docs/course_materials/control_structures.html
> +                  </code></pre>
we have a loop of strings in line 387, and I would like to show the students we can do all options.

2020-09-21 08:59 UTC, sleviim approved these changes
LGTM

2020-09-21 11:14 UTC, merged

2020-09-21 11:16 UTC, rollandf commented
:100: