Add compound data types exe
RedHat-Israel/ROSE pull request #346
Opened 2020-10-05 06:55 UTC by shiramax

2020-10-05 10:45 UTC, sleviim reviewed
Just to be sure - was this one tested?

2020-10-08 07:44 UTC, sleviim requested changes

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/class_exercise_1.md
> +
Remove this extra line and the presentation will work correctly (with the background on the first slide)

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/class_exercise_1.md
> +- Replace the first item with "G"
Please add the image at the end
<div style="text-align:center"><img data-natural-width="340" data-natural-height="234" style="" data-src="https://posteo.de/images/daten.png"/>

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/class_exercise_2.md
> +
same - remove this line and add image

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/class_exercise_3.md
> +    - The student's tests
add image, please

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/homework.md
> +#### Create a list
add 1 line after headline

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/homework.md
> +#### Slicing a list
same

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/homework.md
> +#### Update the list
same

2020-10-08 07:44 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/homework.md
> +### countries.py
same

2020-10-08 08:14 UTC, sleviim commented
Please refer to the other comments as well (add the image at the end of the exe. slides + add 1 line between the headline and the text of the homeworks exe.)

2020-10-08 08:14 UTC, sleviim commented
Also, please resolve the conflicts so it can be merged

2020-10-08 08:23 UTC, shiramax commented on docs/course_materials/exercises/04_Compound_data_types/class_exercise_3.md
> +    - The student's tests
which image?

2020-10-08 08:26 UTC, sleviim commented on docs/course_materials/exercises/04_Compound_data_types/class_exercise_3.md
> +    - The student's tests
&lt<div style="text-align:center"><img data-natural-width="340" data-natural-height="234" style="" data-src="https://posteo.de/images/daten.png"/>&gt

2020-10-13 14:24 UTC, sleviim approved these changes
LGTM
Sorry for all the mess

2020-10-13 14:27 UTC, merged