add python version when running pip env in README
RedHat-Israel/ROSE pull request #349
Opened 2020-10-06 16:47 UTC by shiramax

2020-10-07 07:53 UTC, sleviim requested changes
I thought the machines have python3 installed

2020-10-07 07:53 UTC, sleviim commented on README.md
> +     pipenv --python /usr/local/bin/python3.7 shell
redundant space at the beginning

2020-10-07 07:53 UTC, sleviim commented on README.md
> +     pipenv --python /usr/local/bin/python3.7 shell
same

2020-10-07 08:04 UTC, shiramax commented
@sleviim changing the default version cased a lot of issues in yum command, Ilana and I agree this is a better solution.

2020-10-08 07:17 UTC, sleviim approved these changes

2020-10-11 11:09 UTC, shiramax commented
@sleviim can you merge this one?

2020-10-11 11:46 UTC, merged