Homework exercise navigation page
RedHat-Israel/ROSE pull request #383
Opened 2020-10-31 20:51 UTC by AnnaDinaburgVulikh

1. Created a navigation page for homework exercises.
2. Updated the side menu in course materials to modular form using side-menu.js
3. Linked the homework navigation page to the  Rose main page and to the course materials side bar.

You can view the changes in work here: https://annadinaburgvulikh.github.io/ROSE/ 
by navigating using the homework link after materials or navigating to materials and using the side bar.
Please let me know when to remove the temporary page.

2020-10-31 20:52 UTC, AnnaDinaburgVulikh commented
Hi @shiramax, please let me know if any fixing needed.

2020-11-01 09:09 UTC, shiramax commented
@sleviim it's already exposed in Github.

2020-11-01 09:11 UTC, shiramax commented
@sleviim it's already exposed in Github.
there is no homework at the moment for python intro, we can delete this section for now.

2020-11-01 09:53 UTC, sleviim commented
@shiramax, do we want to expose all homework ahead?
@anna, I think there's something missing with the 'python exercise' link

2020-11-01 10:01 UTC, shiramax requested changes
@AnnaDinaburgVulikh can you add some tests to make sure the links won't break? 
(In case someone will change the names of the files)

2020-11-01 18:15 UTC, AnnaDinaburgVulikh commented on docs/course_materials/exercises/01_Linux/homework_2.md
> +13. Change the name of **my_song.txt** to **your_song.txt** (The file is in ~/hw2/songs).
not intended, I'll copy the latest from the repo

2020-11-02 20:17 UTC, sleviim commented on docs/course_materials/exercises/01_Linux/homework_2.md
> +16. Bonus - Use the command **wc** to print how many lines you have in  ~/hw2/songs/your_song.txt (don't forget to use man).
in  ~/hw2/songs/your_song.txt > remove extra space

2020-11-02 20:27 UTC, AnnaDinaburgVulikh commented
@shiramax @sleviim I hid the link to the homework in the menu under number 9. It's in white on white background, if you hover on you'll see the cursor change.

2020-11-04 20:53 UTC, shiramax approved these changes
Great work @AnnaDinaburgVulikh thanks!

2020-11-07 18:36 UTC, shiramax approved these changes

2020-11-07 18:36 UTC, merged