ROSE: change format to f-string format
RedHat-Israel/ROSE pull request #398
Opened 2020-11-09 13:40 UTC by mgold1234

2020-12-29 09:51 UTC, shiramax commented
@mgold1234 can you please rebase?

2021-01-25 13:34 UTC, rollandf commented on Pipfile
> +python_version = "3.6.8"
Please revert

2021-01-26 08:21 UTC, rollandf commented
@mgold1234 tests are failing

2022-07-09 17:21 UTC, nirs requested changes

2022-07-09 17:21 UTC, nirs commented on rose-admin
> +            log.error(f"Error running: {verb}, {e}")
This is bad change. Logging message should not be formatted. Formatting the messages means we always pay for formatting the logs even when the logs are not enabled (e.g. log.debug() when log level is WARNING).

log.error() is likely always loged, but it does not make sense to handle differently different log messages, so logging calls always pass the arguments to the logger and the logger format the messages before they are written.

Please remove all the changes in logging calls.

2024-01-09 10:29 UTC, closed without merging