ClassRoom API - Adding topic
RedHat-Israel/ROSE pull request #424
Opened 2020-12-23 19:54 UTC by AnnaDinaburgVulikh

Hi @shiramax , added the option for adding topics and retrieving existing ones.
Also updated the README accordingly.
Should I continue to adding ClassWork functionality?

2020-12-27 19:14 UTC, shiramax requested changes
@AnnaDinaburgVulikh Looks great as well, minor changes are needed. 
thanks for your contribution.

2020-12-27 19:14 UTC, shiramax commented on classroom/README.md
> +        `python rose_class.py --course -i --topic -p`
```suggestion
        `python rose_class.py --course -i ID --topic -p`
```

2020-12-27 19:14 UTC, shiramax commented on classroom/README.md
> +        `python rose_class.py --course -i --topic -c "topic name"`
```suggestion
        `python rose_class.py --course -i ID --topic -c "topic name"`

```

2020-12-27 20:57 UTC, AnnaDinaburgVulikh commented
Hi @shiramax , made the fixes. Thanks for the review.

2020-12-28 07:37 UTC, shiramax commented
@AnnaDinaburgVulikh  Can you please rebase?

2020-12-28 14:03 UTC, AnnaDinaburgVulikh commented
Hi @shiramax , rebased and also added a check for valid ID in order to have a nice message instead of an error.

2020-12-28 14:27 UTC, shiramax approved these changes
thanks @AnnaDinaburgVulikh great JOB!

2020-12-28 14:28 UTC, merged