Updated the test homework method and docs
RedHat-Israel/ROSE pull request #429
Opened 2021-05-30 18:33 UTC by AnnaDinaburgVulikh

Hi @sleviim ,
It's the first part of the long pr.
This one includes only the ammended test logic for students homework.

2021-06-06 14:07 UTC, sleviim commented on docs/course_materials/exercises/test_exercises/conftest.py
> +        # testing the code
testing -> Testing

2021-06-06 14:18 UTC, sleviim requested changes
Great work, thanks!
Added some grammar fixes.

I think it would be great if you'll attach a short demo/screenshots for one of the tests you've made.
You can upload it to https://imgur.com/ so it will be available as a link.
What do you think?

2021-06-06 14:18 UTC, sleviim commented on docs/course_materials/exercises/test_exercises/conftest.py
> +                if isinstance(answer[1], list):
isinstance -> isInstance

2021-06-06 14:18 UTC, sleviim commented on docs/course_materials/exercises/test_exercises/conftest.py
> +                                      f'but needs some work:\n{message[:-1]}')
work -> improvments or fixes

2021-06-06 14:18 UTC, sleviim reviewed
remove blanks - Approved :)
Let's wait for the other patch so those would merge together.

2021-06-09 05:13 UTC, AnnaDinaburgVulikh commented on docs/course_materials/exercises/test_exercises/conftest.py
> +                if isinstance(answer[1], list):
it's a builtin function

2021-06-09 11:50 UTC, sleviim approved these changes

2021-06-09 11:50 UTC, merged